-- CreateTable
CREATE TABLE "Pelayanan" (
    "id" SERIAL NOT NULL,
    "tanggal" TEXT NOT NULL,
    "kategori" TEXT NOT NULL,
    "hasilAi" TEXT,
    "ringkasan" TEXT,
    "pesertaId" INTEGER,
    "pemeriksaanId" INTEGER,
    "asiEksklusif" BOOLEAN,
    "mpasi" BOOLEAN,
    "batuk" BOOLEAN,
    "demam" BOOLEAN,
    "bbTidakNaik" BOOLEAN,
    "kontakTBC" BOOLEAN,
    "imunisasi" BOOLEAN,
    "vitaminA" BOOLEAN,
    "obatCacing" BOOLEAN,
    "patuhMT" BOOLEAN,
    "ttd" BOOLEAN,
    "konsumsiTtd" BOOLEAN,
    "mtBumil" BOOLEAN,
    "porsiMt" TEXT,
    "rutinMt" BOOLEAN,
    "penyuluhanTopik" TEXT,
    "ikutKelasIbu" BOOLEAN,
    "waktuDatang" TEXT,
    "batukNifas" BOOLEAN,
    "demamNifas" BOOLEAN,
    "bbTurunNifas" BOOLEAN,
    "kontakTBCNifas" BOOLEAN,
    "jumlahKapsul" TEXT,
    "konsumsiVitaminA" BOOLEAN,
    "menyusui" BOOLEAN,
    "kbPasca" BOOLEAN,
    "topikPenyuluhanNifas" TEXT,
    "batukRemaja" BOOLEAN,
    "demamRemaja" BOOLEAN,
    "bbTurunRemaja" BOOLEAN,
    "kontakTBCRemaja" BOOLEAN,
    "penyuluhanRemaja" BOOLEAN,
    "topikPenyuluhanRemaja" TEXT,
    "mataKanan" TEXT,
    "mataKiri" TEXT,
    "telingaKanan" TEXT,
    "telingaKiri" TEXT,
    "kadarHb" TEXT,
    "batukLansia" BOOLEAN,
    "demamLansia" BOOLEAN,
    "bbTurunLansia" BOOLEAN,
    "kontakTBCLansia" BOOLEAN,
    "tekananDarah" TEXT,
    "gulaDarah" TEXT,
    "kolesterol" TEXT,
    "penyuluhanLansia" BOOLEAN,
    "topikPenyuluhanLansia" TEXT,
    "orientasi" BOOLEAN,
    "ingatKata" BOOLEAN,
    "tesBerdiri" BOOLEAN,
    "bbTurun3kg" BOOLEAN,
    "nafsuMakan" BOOLEAN,
    "lila" BOOLEAN,
    "masalahMata" BOOLEAN,
    "tesMelihat" BOOLEAN,
    "tesBerbisik" BOOLEAN,
    "sedih" BOOLEAN,
    "minat" BOOLEAN,
    "imunisasiCovid" BOOLEAN,
    "topikPenyuluhanSkilas" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Pelayanan_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Pelayanan" ADD CONSTRAINT "Pelayanan_pesertaId_fkey" FOREIGN KEY ("pesertaId") REFERENCES "Peserta"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Pelayanan" ADD CONSTRAINT "Pelayanan_pemeriksaanId_fkey" FOREIGN KEY ("pemeriksaanId") REFERENCES "Pemeriksaan"("id") ON DELETE SET NULL ON UPDATE CASCADE;
